Feat/eda/tiwari6 eda
katldewitt/house_price_prediction pull request #20
Opened 2022-07-27 19:45 UTC by reach2avi

PR for helper functions

2022-07-30 21:56 UTC, reach2avi commented on 200_Final_Report/102_avi.Rmd
> +plot_qq = function(model, model_name, pointcol = "dodgerblue", linecol = "darkorange") {
@katldewitt if you could clarify this point a bit more

2022-07-30 22:26 UTC, reach2avi commented
> @reach2avi I am not added as a reviewer on this pull request, so GitHub doesn't give me ability me to review and add comments.

just assigned - you should be able to review now. thanks

2022-07-31 02:29 UTC, thakur-shashank commented on 200_Final_Report/102_avi.Rmd
> +plot_qq = function(model, model_name, pointcol = "dodgerblue", linecol = "darkorange") {
There is delivered function `plot()` which can be used to get residuals vs fitted. I have used it under Model Selection in the modeling RMD if you want to review. I believe you can use `par` to just print Residuals vs Fitted and Q-Q plot. You may need to explore more.

2022-07-31 02:33 UTC, thakur-shashank commented on 200_Final_Report/102_avi.Rmd
> -## QA: How do we know what we did makes sense?.
The numeric response variable in CA Housing data set is not suitable of using logistic regression. So we can't use confusion matrix and sensitivity/specificity functions as you've defined them. I'll leave it up to you to decide if you want it in this EDA. My recommendation will be to just keep helper functions that we've used for some of our tasks. There isn't a good reason to have all these helper functions.

2022-07-31 02:34 UTC, thakur-shashank requested changes
@reach2avi I have reviewed this PR and provided my inputs for changes. You can merge it based on how you want to proceed. Thanks!

2022-07-31 03:17 UTC, reach2avi commented on 200_Final_Report/102_avi.Rmd
> -## QA: How do we know what we did makes sense?.
@thakur-shashank 
i agree. i will conf_matrix, sens / spec can be easily removed. kept it as reference in the begining. thinking of toolbox kind of approach - keeping all the tools in this section. but we decided to be specific in our code. even in appendix helper functions related to logistic wont help. so will delete these 3

2022-07-31 03:29 UTC, reach2avi commented on 200_Final_Report/102_avi.Rmd
> +plot_qq = function(model, model_name, pointcol = "dodgerblue", linecol = "darkorange") {
@thakur-shashank 
104_sthakur5_modelling? the one below?

par(mfrow=c(2, 2))

plot(cahoudta_full_add_model,
     pch = 20,
     col = "lightgoldenrod2")

2022-07-31 05:45 UTC, katldewitt commented on 200_Final_Report/102_avi.Rmd
> +plot_qq = function(model, model_name, pointcol = "dodgerblue", linecol = "darkorange") {
The driver function model_plots does not have the ability to change colors via parameters, but plot_qq and plot_fitted_resid do. This means the inner function have parameters that are unchangeable via the outer function. As such, my recommendation is to remove the colors from the parameter list in the inner functions and hard code them in the function. See example below

```
  plot(fitted(model), resid(model), col = "dodgerblue" , pch = 20, cex = 1.5, xlab = "Fitted", ylab = "Residuals", main = "Fitted vs. Residual", sub = model_name)

```

2022-07-31 08:33 UTC, reach2avi commented on 200_Final_Report/102_avi.Rmd
> +plot_qq = function(model, model_name, pointcol = "dodgerblue", linecol = "darkorange") {
updated to hard code inner function

2022-08-01 18:12 UTC, thakur-shashank approved these changes
As we discussed on Slack, all good to publish and close the PR.

2022-08-01 18:14 UTC, reach2avi commented
@thakur-shashank @katldewitt closing this PR by merging pull request. thanks

2022-08-01 18:15 UTC, merged